M48
; DRILL file {KiCad (7.0.0)} date Tue Mar 21 01:24:05 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-21T01:24:05-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1299
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1457
%
G90
G05
T1
X5.5035Y-5.4716
X5.6945Y-5.4716
T2
X5.4917Y-5.5909
X5.7063Y-5.5909
T3
X4.6458Y-4.7644
X4.6458Y-5.2144
T4
X4.7449Y-3.35
X4.7449Y-5.501
X6.955Y-3.35
X6.955Y-5.502
T0
M30
