M48
; DRILL file {KiCad (6.0.5)} date Thu May  5 21:27:12 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-05-05T21:27:12-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.250
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.700
%
G90
G05
T1
X133.84Y-79.65
X145.27Y-79.65
T2
X151.75Y-80.11
X161.91Y-80.11
X167.75Y-80.11
X177.91Y-80.11
T3
X125.0Y-63.0
X125.0Y-140.0
X176.0Y-63.0
X176.0Y-140.0
T0
M30
